### ISSUE TITLE
Opcode A9 is LDA #, not TAY #

### ISSUE THREAD

**Issue by TobyLobster** [shawty/BBCB_DFS_Catalog#3]
The current code disassembles $A9 as a "TAY #" but this should be "LDA #" (see line "ops[0xA9] = ['TAY #' , 4];").

**Comment by shawty** [comment]
Hi @TobyLobster :-)

Yes I'm aware of that thanks.  The code that's there was written by someone else as an addition to my original DFS Catalog, which didn't have file viewing capabilities.

Iv'e since taken those changes folded them in, with the intention of fixing all these small niggles and making it more modular.

I've just not had time to do anything with it yet.

I'll leave this open however as a reminder that it needs doing.

Thanks.

**Comment by kieranhj** [comment]
The disassembly also displays ZP addressing mode in brackets, even when it's not indirect, which is really confusing!

**Comment by shawty** [comment]
hi @kieranhj thanks, noted.  i'm actually re-writing it all from scratch as/where time permits.

can you add this as a new issue please, so i can keep track of individual bugs.

cheers
shawty

**Comment by kieranhj** [comment]
Done. This is a super cool tool BTW. Only just discovered it on bbcmicro.co.uk. Good work!

**Comment by shawty** [comment]
@kieranhj Thanks.

Originally as I've said elsewhere, I only wrote the DFS Disk image stuff, some other BBC Enthusiasts wrote the viewer parts.  Given the age of the code I've decided to re-write in a more modern language (C#) using Microsoft's new Blazor Web Assembly which will also allow me to build the thing as an offline accessible PWA/Mobile/Desktop app.

I wrote it originally for 8BS.com (You can still find the original version there, along with some PHP access routines for working with DFS images), and the guys at the BBC Games index decided to use it too and modified it. :-)

It helped me to, as someone who's been involved with the BBC Micro since it's inception back in the early 1980's I've amassed a large collection of floppy disk images, so I needed it for my own internal systems to keep track of what I had :-)

I've just put an update on the front page, do keep the bug reports and suggestions coming, I'll do my best to get some traction on the project as soon as I can.

**Comment by pau1ie** [comment]
I wrote the disassembly. I note someone else has fixed the bug on bbcmicro. I will try to get a PR with this fix.
